// <auto-generated />
using BibliotekaProjekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotekaProjekt.Migrations
{
    [DbContext(typeof(BibliotekaContext))]
    [Migration("20251230202542_DodanieEbookowDoContextu")]
    partial class DodanieEbookowDoContextu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BibliotekaProjekt.Models.Zasob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyWypozyczony")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("RokWydania")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zasoby");

                    b.HasDiscriminator().HasValue("Zasob");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BibliotekaProjekt.Models.Ebook", b =>
                {
                    b.HasBaseType("BibliotekaProjekt.Models.Zasob");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LiczbaStron")
                        .HasColumnType("INTEGER");

                    b.ToTable("Zasoby", t =>
                        {
                            t.Property("Autor")
                                .HasColumnName("Ebook_Autor");

                            t.Property("LiczbaStron")
                                .HasColumnName("Ebook_LiczbaStron");
                        });

                    b.HasDiscriminator().HasValue("Ebook");
                });

            modelBuilder.Entity("BibliotekaProjekt.Models.Film", b =>
                {
                    b.HasBaseType("BibliotekaProjekt.Models.Zasob");

                    b.Property<int>("CzasTrwaniaMinuty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rezyser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Film");
                });

            modelBuilder.Entity("BibliotekaProjekt.Models.Ksiazka", b =>
                {
                    b.HasBaseType("BibliotekaProjekt.Models.Zasob");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LiczbaStron")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Ksiazka");
                });
#pragma warning restore 612, 618
        }
    }
}
